### ISSUE TITLE
Implementing TLS Extension for Certificate Transparency

### ISSUE THREAD

**Issue by droptableuser** [nabla-c0d3/nassl#4]
Hi,

I am looking to implement the usage of the TLS Extension for Certificate Transparency. 
From openssl itself it can be queried like that:
`openssl s_client -serverinfo 18  -connect google.com:443 </dev/null 2>/dev/null | sed -n -e "/BEGIN SERVERINFO/,/END SERVERINFO/p"`

The SCT is only sent if the client signals the support for the extension per https://tools.ietf.org/html/rfc6962#section-3.3.1

Further methods to serve the SCT is via OCSP or directly inside the Certificate. The SCT included in the OCSP response can be parsed already form the response and I will send in a pull request after I cleaned it up a little bit. 

Where would I start to implement this feature?

Kind Regards.

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for the help!
* For the TLS extension, the best approach is to look at how `s_client` is doing it, and then add a wrapper for the same functions in `nassl._nassl` (the C extension) so they can be called from Python. Hopefully this doesn't require wrapping too many functions. You might run into problems if these functions require a more recent version of OpenSSL, but let me know.
* For the certificate method, I am in the process of removing some of the code that tries to parse certificates in `X509Certificate` because it is too buggy and also too much work to maintain. I will instead use https://github.com/pyca/cryptography for my projects (mainly SSLyze), which I think already support the SCT certificate extension.
* For the OCSP one, it looks like you already have something working?

Let me know your thoughts!

**Comment by droptableuser** [comment]
Hi,

It took some time to actually come around to do so work on this. Sadly the OpenSSL version used does not support the extension required. Is there a easy way to use to update the lilbrary?

Best!

**Comment by nabla-c0d3** [comment]
Moving to OpenSSL 1.1.0+ is on the roadmap but that's a big change; not going to happen soon.

**Comment by droptableuser** [comment]
Thanks!
