### ISSUE TITLE
nassl / sslyze PKGBUILD

### ISSUE THREAD

**Issue by baerbock** [nabla-c0d3/nassl#55]
Dear nable,

I'm trying to fix the sslyze [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sslyze-git ) for ArchLinux, which curently doesn't build successfully.

For this I can't rely on `pipenv`, so an installation using classic `setup.py` would be helpful.

**Comment by nabla-c0d3** [comment]
Hello,
You can either use `pip install nassl` or implement a script similar to https://github.com/nabla-c0d3/nassl/blob/master/build_linux_wheels.sh (but where you only build once instead of multiple times). There is no way to do a "full" build without pipenv/invoke because the process is too complicated to be implemented with just `setup.py` command. Good luck!
