### ISSUE TITLE
Support for dynamic linking of OpenSSL

### ISSUE THREAD

**Issue by veehaitch** [nabla-c0d3/nassl#64]
First of all, thanks for your great work!

I'm currently working on bringing SSLyze into [Nix](https://github.com/NixOS/nixpkgs/pull/89034). As Nassl is a dependency of SSLyze, I also had to create a package for it first. In the review of the PR, [the question came up](https://github.com/NixOS/nixpkgs/pull/89034#discussion_r435734351), if there's any way to dynamically link Nassl against the system OpenSSL version, at least for the modern OpenSSL suite.

Thanks!

**Comment by jtojnar** [comment]
Looking at the source code it is linked somewhat reasonably:

https://github.com/nabla-c0d3/nassl/blob/ffdee9dccbf32bffa3da531b80fe3fdfd6c36659/setup.py#L100-L106

One thing I would change, have `LegacyOpenSslBuildConfig` export `extra_objects`, `extra_link_flags` and other useful [`Extension`](https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension) kwargs, instead of handling zlib in `setup.py` (it is a dependency of OpenSSL so nassl should not really care about zlib; modern build system like Meson or CMake would allow you to abstract that too).

Then we could have a flag to use system dependencies, which would make `LegacyOpenSslBuildConfig` return flags obtained using [`pkg-config`](https://pypi.org/project/pkgconfig/):

```python
extra_compile_args -> pkgconfig.cflags('openssl') + ' ' + pkgconfig.cflags('libcrypto')
extra_link_args -> pkgconfig.libs('openssl') + ' ' + pkgconfig.libs('libcrypto')
```

**Comment by nabla-c0d3** [comment]
Hello,

Thanks for the interest :) To be honest I would advise against dynamically linking OpenSSL for at least three reasons:

1) It will force the OS to install a really insecure version of OpenSSL (the "legacy" one as called by nassl).
2) Nassl not only requires specific versions of OpenSSL, but also specific build flags to enable insecure algorithms (such as MD2). It might still work without these build flags but the security testing will not be as good.
3) Setting up the right scripts to get these specific versions of OpenSSL to build correctly on Linux, macOS and Windows was tricky. I will not have the bandwidth to add and maintain another way to build or link OpenSSL to nassl.

Why not just support installing sslyze via pip?

**Comment by vcunat** [comment]
(1.) does not apply to Nix packages.  Visibility by one package does not imply visibility by others.  On the other hand, dynamic linkage has no real point if there's only one ELF using the library (but I generally don't expect issues from that).

**Comment by veehaitch** [comment]
We've merged this as is into Nixpkgs. Still, would be great to see the proposed improvements to the build process in the future. Again, thanks for this useful project.
